### PR TITLE
MINTmap.pl now reads fastq.gz files and searches for the full lengt tRNA

### PR DESCRIPTION
**Pull request by stela2502**
Hi,
thank you for this excellent tool!
I have added two simple additions to MINTmap which you might want to include in your tool:
(1) MINTmap.pl can now handle gzipped fastq files.
(2) MINTmap.pl now by default searches for the full length tRNA too.

I hope you like the changes.

Sincerely,
/Stefan

### CODE REVIEW

**Review by phillipeloher — CHANGES_REQUESTED** [review]
Hi Stefan, thank you, we are glad you like the tool!  Right now the tool makes many assumptions that are only applicable to tRNA fragments that won't work with full length tRNA.  Introducing full length tRNA would likely be problematic for a number of reasons such as (a) normalization concerns (b) exact-match (no mismatches/indels) would be more problematic (c) naming convention for fragments wouldn't match full length naming conventions  (d) post-modification handling likely wouldn't work.  For such reasons, I'm going to close out this request.  For mapping full length tRNA's I would suggest a different tool or mapper.  That being said, if you have any improvements that improve the profiling of tRFs we would be very happy to incorporate them in.  Going forward, we will update our readme file in the next revision to help clarify what changes are most appropriate for the tool.

**Review by phillipeloher — CHANGES_REQUESTED** [review]
Hi Stefan, thank you, we are glad you like the tool!  Right now the tool makes many assumptions that are only applicable to tRNA fragments that won't work with full length tRNA.  Introducing full length tRNA would likely be problematic for a number of reasons such as (a) normalization concerns (b) exact-match (no mismatches/indels) would be more problematic (c) naming convention for fragments wouldn't match full length naming conventions  (d) post-modification handling likely wouldn't work.  For such reasons, I'm going to close out this request.  For mapping full length tRNA's I would suggest a different tool or mapper.  That being said, if you have any improvements that improve the profiling of tRFs we would be very happy to incorporate them in.  Going forward, we will update our readme file in the next revision to help clarify what changes are most appropriate for the tool.

**Comment by stela2502** [comment]
Hi Phillipe,

We are interested in the fraction of tRNA fragment versus full length 
tRNA. Do you think my approach to simply include the full length tRNA 
entries into the analysis would create problems for the rest of the 
data? Like messing up the normalization?

To my knowledge we are at the moment not interested in 
post-modifications for the full length fragment. Of cause you are right, 
that simply identifying the full length would be tricky regarding the 
read errors.

Apart from that I added a merger for the outfiles to my fork and made 
the tool installable:

make
make install

Oh and please let me know if I am rude modifying your code like that 
(https://github.com/stela2502/MINTmap). I can take down/rename the fork 
whenever you want.


/Stefan

**Comment by phillipeloher** [comment]
Hi Stefan,
The lookup table LookupTable.tRFs.MINTmap_v1.txt contains all possible tRF's and information on whether or not each of the tRF's are exclusive to tRNA space.  The short RNA dataset being profiled/mapped (after quality and adaptor trimming) are then compared to segments in that file.  If sequences exist in that file that are longer that the read length or tRF lengths, they won't contribute to any quantification.  If you are adding brand new tRNA's, you'd have to break them into all their possible tRF's and recompute the lookup table as outlined in the Methods.  Unfortunately creating the lookup table is a somewhat time consuming method but you only have to compute it once for the tRNA reference set of interest.

**Pull request closed without merging**
